apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          uname -m
      - name: Print CLI versions
        uses: docker://swashbuck1r/cbp-agent-registry-custom-job:0.0.1
        shell: bash
        run: |
          echo "hello6"
          ls -al
          set -x
          /app/cbp-agent-registry-custom-job --handler "init"
  custom-approval:
    timeout-minutes: 4320
    delegates: swashbuck1r/custom-jobs/custom-job.yml@main
    with:
      adminToken: ${{ secrets.CBP_AGENT_REGISTRY_TOKEN }}
      tenantId: "tenant-123"
      jobType: "shell"
      jobData: |
        {
          "command": "ls -al"
        }
      timeout: 600
